pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo "Builing.."
                withMaven(maven: 'maven') {
                 sh 'mvn -B -DskipTests clean package'
              }
            }
        }

    }
}
